platform: rest
resource: !secret application_shopper_gaze_monitor_cpp_demo
name: Application Shopper Gaze Monitor CPP Demo
body_on: '{"state": "start"}'
body_off: '{"state": "stop"}'
is_on_template: '{{ value_json is not none and value_json.state == "running" }}'
